services:
  firegen:
    build: .
    container_name: firegen
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=firegen.dev,www.firegen.dev
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=firegen.dev,www.firegen.dev
    networks:
      - proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "25M"

networks:
  proxy:
    name: proxy
    external: true
